
mysql.datasource:
  jdbc-url: jdbc:mysql://localhost:3306/local_mysql
  username: admin
  password: admin
  driver-class-name: org.mariadb.jdbc.Driver

postgresql.datasource:
  jdbc-url: jdbc:postgresql://localhost:5432/local_postgresql
  username: admin
  password: admin
  driver-class-name: org.postgresql.Driver

mssql.datasource:
  jdbc-url: jdbc:sqlserver://localhost:1433
  username: sa
  password: administrator123!
  driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
